name: Auto-merge Dependabot PRs with green build

on:
  pull_request:
    types: [opened, labeled, synchronize]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "automatic"
